### ISSUE TITLE
Headsets Which Don't Work

### ISSUE THREAD

**Issue by goliver1984** [goliver1984/afv-issues#5]
The following headsets appear to not show up as devices:-

-Scarlet
-Razen
-VoiceMeeta

**Comment by NelisV** [comment]
regarding the Focusrite Scarlett: i've been looking around and it seems it has something to do with that this device handles both in and output in my case. output device is detected correctly by AFV and can be used but the input field remains empty. 

https://forum.juce.com/t/wasapi-exclusive-or-asio-devices-have-no-input-channels-why/31482/4
it seems it has something to do with correctly initializing (or refreshing) the amount of channels on a device. would be great if this can be fixed :) 

quote from: https://github.com/WeAreROLI/JUCE/pull/497
"It turns out that what was going wrong was:

- AudioDeviceManager::AudioDeviceManager() has initializers for numInputChansNeeded (0), and numOutputChansNeeded (2).

- My code calls setCurrentAudioDeviceType("ASIO", false).

    - This winds up calling AudioDeviceManager::setAudioDeviceSetup.
    - That setup call has an "if" clause at line 476 which checks if device names changed or there is no current device.
        - Since there is no current device, the if branch is taken.
        - This initializes AudioDeviceManager::inputChannels to (bitset value) 0 and AudioDeviceManager::outputChannels to (bitset value) 3, which is correct given the existing constructed values of num{In,Out}putChansNeeded.
- My code then calls initialiseWithDefaultDevices(2, 2).
    - This again winds up calling AudioDeviceManager::setAudioDeviceSetup.
    - However, this time, the "if" clause at line 476 is not taken.
        - This is because the ASIO device has already been set up and the input and output device names have not changed.

The result: even though the device manager's numInputChansNeeded is finally set to 2, the device manager's inputChannels bitset is still at 0, preventing input."

**Comment by goliver1984** [comment]
fixed
